# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: PyTest Workflow

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  pytest:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install Dependencies
        run: pip install -r requirements.txt  # Replace with your requirements file

      - name: Run PyTest
        run: pytest  # Run all tests in the repository

      - name: Run PyTest with HTML report
        run: |
          pytest --html=report.html
        env:
          PYTEST_ADDOPTS: "--html=report.html"

      - name: Upload HTML Report as Artifact
        uses: actions/upload-artifact@v2
        with:
          name: pytest-html-report
          path: report.html
